title: Mollie# your name (or website title) here
<img src="Users/molliepassacantando/git_repos/mollie-passacantando.github.io/images/mollie_fishpic.jpeg"> 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Student in Physical Oceanography 
  <br><br>
  University of Rhode Island
 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
